#!/usr/bin/env bash

if [[ -z $REPO_DIR ]]; then
    REPO_DIR=$HOME/code/.dotfiles
fi

## Install homebrew
if ! command -v brew &> /dev/null; then
	echo "Homebrew is not installed. Starting install of Homebrew."
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
	echo "Homebrew is already installed, skipping install of Homebrew"
fi

REPO_DIR=$REPO_DIR $REPO_DIR/install.sh --mac "$@"
