#!/usr/bin/env zsh

## We were ignoring the .config folder and other .folders by default and I don't want to do that when searching project files in a directory
export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix --hidden --follow --exclude .git'

source <(fzf --zsh)
